# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b6883cffb6732a6a456ce5007b554d103a10e4de4437f4add44a25ec7942588731c68bacf39eff4e7b38d62d10bd56bf8ffcbef070f4a5e772d6003e781653c

test:
  secret_key_base: 506360d678c3c8d3e0497c253df67063ff512cc56f42934b14e2424996d690eb9eea697d0e26b7688c378c2ddde68b9c31dcadacdabd1438399357f28b5585ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
